---
micronaut:
  application:
    name: conference
  security:
    enabled: false
  server.port: -1
#---
#tracing:
#  zipkin:
#    enabled: true
#    http:
#      url: http://localhost:9411
#    sampler:
#      probability: 0.1
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

conferences:
    mongo:
        database: jfall
        collection: conferences

endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
info:
  app:
    name: ${micronaut.application.name}
